// <auto-generated />
using System;
using Jenian.Infrastructure.Persistence.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jenian.Infrastructure.Persistence.Migrations.JenianDb
{
    [DbContext(typeof(JenianDbContext))]
    [Migration("20260212235252_UpdateEodReportAndDeliveryExtractionJob")]
    partial class UpdateEodReportAndDeliveryExtractionJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JenianAPI.Models.BackgroundJobsModels.DeliveryExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryExtractionJobs");
                });

            modelBuilder.Entity("JenianAPI.Models.JenianModels.EodReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Delivery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EodReports");
                });

            modelBuilder.Entity("JenianAPI.Models.JenianModels.EodReport", b =>
                {
                    b.OwnsOne("JenianAPI.Models.JenianModels.AislesFacing", "AislesFacing", b1 =>
                        {
                            b1.Property<Guid>("EodReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BabyFirstAid")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Backwall")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Cosmetics")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FemHygSummer")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Fragrances")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FrontCounter")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Haircare")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PSA")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Skincare")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SportNutritions")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Vitamins")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EodReportId");

                            b1.ToTable("EodReports");

                            b1.WithOwner()
                                .HasForeignKey("EodReportId");
                        });

                    b.OwnsOne("JenianAPI.Models.JenianModels.Cleaning", "Cleaning", b1 =>
                        {
                            b1.Property<Guid>("EodReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BinRun")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ConsultingRoom")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Sweeping")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TeaRoom")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EodReportId");

                            b1.ToTable("EodReports");

                            b1.WithOwner()
                                .HasForeignKey("EodReportId");
                        });

                    b.OwnsOne("JenianAPI.Models.JenianModels.GeneralCheck", "GeneralCheck", b1 =>
                        {
                            b1.Property<Guid>("EodReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FreeCages")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FreeTrolleys")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumOfAugmodos")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("NumOfCataBundle")
                                .HasColumnType("int");

                            b1.Property<int>("NumOfClickCollect")
                                .HasColumnType("int");

                            b1.Property<string>("NumOfFragKeys")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumOfLiftPasses")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("NumOfMagaBundle")
                                .HasColumnType("int");

                            b1.Property<string>("NumOfMyPals")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EodReportId");

                            b1.ToTable("EodReports");

                            b1.WithOwner()
                                .HasForeignKey("EodReportId");
                        });

                    b.OwnsOne("JenianAPI.Models.JenianModels.NightTasks", "NightTasks", b1 =>
                        {
                            b1.Property<Guid>("EodReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BatWings")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Catalogue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ClipStrips")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DispLedge")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FloorStack")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Gondolas")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LowLevel")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Mesh")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Podiums")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Sunglasses")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Tills")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TopSellers")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EodReportId");

                            b1.ToTable("EodReports");

                            b1.WithOwner()
                                .HasForeignKey("EodReportId");
                        });

                    b.OwnsOne("JenianAPI.Models.JenianModels.StockUpdate", "StockUpdate", b1 =>
                        {
                            b1.Property<Guid>("EodReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdditionalNote")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("AdditionalStock")
                                .HasColumnType("int");

                            b1.Property<string>("CosmeticNote")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FragranceNote")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StockNote")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("TrolleyOfCosmetics")
                                .HasColumnType("int");

                            b1.Property<int>("TrolleyOfStock")
                                .HasColumnType("int");

                            b1.Property<int>("TrolleyofFragrances")
                                .HasColumnType("int");

                            b1.HasKey("EodReportId");

                            b1.ToTable("EodReports");

                            b1.WithOwner()
                                .HasForeignKey("EodReportId");
                        });

                    b.Navigation("AislesFacing")
                        .IsRequired();

                    b.Navigation("Cleaning")
                        .IsRequired();

                    b.Navigation("GeneralCheck")
                        .IsRequired();

                    b.Navigation("NightTasks")
                        .IsRequired();

                    b.Navigation("StockUpdate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
